### ISSUE TITLE
Installing climextRemes from pip 

### ISSUE THREAD

**Issue by malininae** [cran/climextRemes#1]
Hi, I'm trying to install climextremes into my environment using pip and there seems to be an issue, because neither the system's internal compiler, no compiler installed with the environment appears to be working. 

`Command: pip install climextremes`

```
Collecting climextremes
  Using cached climextremes-0.3.1-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: numpy in ~/miniconda3/envs/rapid_event_climex_test/lib/python3.10/site-packages (from climextremes) (1.26.4)
Requirement already satisfied: pandas in ~/miniconda3/envs/rapid_event_climex_test/lib/python3.10/site-packages (from climextremes) (2.2.2)
Collecting rpy2 (from climextremes)
  Using cached rpy2-3.5.16.tar.gz (220 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [77 lines of output]
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libgomp.so.1: undefined reference to `clock_getres@GLIBC_2.17'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `__nanosleep_nocancel@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: ~/miniconda3/envs/rapid_event_climex_test/lib/R/lib/../../libreadline.so.8: undefined reference to `tgoto@NCURSES6_TINFO_5.0.19991023'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: ~/miniconda3/envs/rapid_event_climex_test/lib/R/lib/../../libreadline.so.8: undefined reference to `UP@NCURSES6_TINFO_5.0.19991023'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libtinfo.so.6: undefined reference to `__poll_chk@GLIBC_2.16'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `__twalk@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libgomp.so.1: undefined reference to `aligned_alloc@GLIBC_2.16'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: ~/miniconda3/envs/rapid_event_climex_test/lib/R/lib/../../libreadline.so.8: undefined reference to `tgetent@NCURSES6_TINFO_5.0.19991023'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: ~/miniconda3/envs/rapid_event_climex_test/lib/R/lib/../../libreadline.so.8: undefined reference to `tgetnum@NCURSES6_TINFO_5.0.19991023'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libquadmath.so.0: undefined reference to `__signgam@GLIBC_2.23'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: ~/miniconda3/envs/rapid_event_climex_test/lib/R/lib/../../libreadline.so.8: undefined reference to `PC@NCURSES6_TINFO_5.0.19991023'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libgomp.so.1: undefined reference to `memcpy@GLIBC_2.14'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `__call_tls_dtors@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `__tsearch@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `__clock_gettime@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: ~/miniconda3/envs/rapid_event_climex_test/lib/R/lib/../../libreadline.so.8: undefined reference to `tgetstr@NCURSES6_TINFO_5.0.19991023'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `__mmap@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libstdc++.so.6: undefined reference to `__cxa_thread_atexit_impl@GLIBC_2.18'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libgomp.so.1: undefined reference to `clock_gettime@GLIBC_2.17'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `__tdelete@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `__h_errno@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `_IO_enable_locks@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `__mktemp@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `__tfind@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: ~/miniconda3/envs/rapid_event_climex_test/lib/R/lib/../../libreadline.so.8: undefined reference to `tgetflag@NCURSES6_TINFO_5.0.19991023'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `__madvise@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `__sigtimedwait@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `__libc_fcntl64@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `__getrlimit@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: ~/miniconda3/envs/rapid_event_climex_test/lib/libicuuc.so: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `__pause_nocancel@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libgfortran.so.5: undefined reference to `expf@GLIBC_2.27'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `__tunable_get_val@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `__write_nocancel@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `__ctype_init@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `__mprotect@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libgomp.so.1: undefined reference to `secure_getenv@GLIBC_2.17'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `__munmap@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: ~/miniconda3/envs/rapid_event_climex_test/lib/R/lib/../../libreadline.so.8: undefined reference to `BC@NCURSES6_TINFO_5.0.19991023'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `__open64_nocancel@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `__read_nocancel@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libpthread.so.0: undefined reference to `__close_nocancel@GLIBC_PRIVATE'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: ~/miniconda3/envs/rapid_event_climex_test/lib/R/lib/../../libreadline.so.8: undefined reference to `tputs@NCURSES6_TINFO_5.0.19991023'
      ~/miniconda3/envs/rapid_event_climex_test/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /lib64/libgfortran.so.5: undefined reference to `logf@GLIBC_2.27'
      collect2: error: ld returned 1 exit status
      Traceback (most recent call last):
        File "/var/tmp/pbs.306313021.ppp5pbs-001-ib/pip-build-env-kygizi6_/overlay/lib/python3.10/site-packages/setuptools/_distutils/unixccompiler.py", line 269, in link
          self.spawn(linker + ld_args)
        File "/var/tmp/pbs.306313021.ppp5pbs-001-ib/pip-build-env-kygizi6_/overlay/lib/python3.10/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/var/tmp/pbs.306313021.ppp5pbs-001-ib/pip-build-env-kygizi6_/overlay/lib/python3.10/site-packages/setuptools/_distutils/spawn.py", line 68, in spawn
          raise DistutilsExecError(f"command {cmd!r} failed with exit code {exitcode}")
      distutils.errors.DistutilsExecError: command '~/miniconda3/envs/rapid_event_climex_test/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "~/miniconda3/envs/rapid_event_climex_test/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "~/miniconda3/envs/rapid_event_climex_test/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "~/miniconda3/envs/rapid_event_climex_test/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/var/tmp/pbs.306313021.ppp5pbs-001-ib/pip-build-env-kygizi6_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/var/tmp/pbs.306313021.ppp5pbs-001-ib/pip-build-env-kygizi6_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/var/tmp/pbs.306313021.ppp5pbs-001-ib/pip-build-env-kygizi6_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 141, in <module>
        File "<string>", line 121, in get_r_c_extension_status
        File "<string>", line 82, in get_c_extension_status
        File "/var/tmp/pbs.306313021.ppp5pbs-001-ib/pip-build-env-kygizi6_/overlay/lib/python3.10/site-packages/setuptools/_distutils/ccompiler.py", line 781, in link_executable
          self.link(
        File "/var/tmp/pbs.306313021.ppp5pbs-001-ib/pip-build-env-kygizi6_/overlay/lib/python3.10/site-packages/setuptools/_distutils/unixccompiler.py", line 271, in link
          raise LinkError(msg)
      distutils.errors.LinkError: command '~/miniconda3/envs/rapid_event_climex_test/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

Any ideas on how to fix it?

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by malininae** [comment]
> Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

Apologies I haven't notices I used CRAN and not the source channel, please, delete the issue!

**Comment by valeriupredoi** [comment]
cheers @gaborcsardi - for the record the repo is a Bitbucket repo https://bitbucket.org/lbl-cascade/climextremes-dev/src/master/ and we are trying to use the conda deployment anyway, via:
```
mamba install -c conda-forge -c cascade climextremes
```
Many thanks both!
